all: build
	open -a "Google Chrome" http://127.0.0.1:4000
	jekyll serve --watch

build:
	jekyll build

install:
	gem install bundler
	gem install jekyll
	gem install jekyll-mentions

ruby.mac:
	brew install ruby
