#[gcc]
blacklist /usr/include
blacklist /usr/bin/gcc*
blacklist /usr/bin/cpp*
blacklist /usr/bin/c9*
blacklist /usr/bin/c8*
blacklist /usr/bin/c++*
blacklist /usr/bin/ld
blacklist /usr/bin/gdb

#[clang/llvm]
blacklist /usr/bin/clang*
blacklist /usr/bin/llvm*
blacklist /usb/bin/lldb*
blacklist /usr/lib/llvm*

#[valgrind]
blacklist /usr/bin/valgrind*
blacklist /usr/lib/valgrind

#[perl]
blacklist /usr/bin/perl
blacklist /usr/bin/cpan*
blacklist /usr/share/perl*
blacklist /usr/lib/perl*

#[php]
blacklist /usr/bin/php*
blacklist /usr/share/php*
blacklist /usr/lib/php*

#[ruby]
blacklist /usr/bin/ruby
blacklist /usr/lib/ruby
